// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // last_hurrah
global.__objectDepths[1] = -2002; // last_hurrahtext
global.__objectDepths[2] = 0; // ch_selector
global.__objectDepths[3] = 0; // chal_butt1
global.__objectDepths[4] = 0; // chal_butt2
global.__objectDepths[5] = 0; // chal_butt3
global.__objectDepths[6] = 0; // chal_butt4
global.__objectDepths[7] = 0; // chal_butt5
global.__objectDepths[8] = 0; // ch_openfile
global.__objectDepths[9] = 0; // ch_text_above
global.__objectDepths[10] = 0; // Gamerule
global.__objectDepths[11] = 0; // window_controller
global.__objectDepths[12] = 0; // lock_setting
global.__objectDepths[13] = 0; // icelock_setting
global.__objectDepths[14] = 0; // coal_control
global.__objectDepths[15] = 0; // doom_setting
global.__objectDepths[16] = 0; // particle_control
global.__objectDepths[17] = 0; // indicator_control
global.__objectDepths[18] = 0; // options_master
global.__objectDepths[19] = 0; // options_volumemus
global.__objectDepths[20] = 0; // options_volumefx
global.__objectDepths[21] = 0; // options_chk_vsync
global.__objectDepths[22] = 0; // options_chk_2dlight
global.__objectDepths[23] = 0; // obj_challenger
global.__objectDepths[24] = 0; // obj_load
global.__objectDepths[25] = 0; // but_options
global.__objectDepths[26] = -1; // but_back
global.__objectDepths[27] = -2001; // wheel_spinner
global.__objectDepths[28] = -2000; // blackfade
global.__objectDepths[29] = -2002; // wheel_butt
global.__objectDepths[30] = 0; // butt_classic
global.__objectDepths[31] = 0; // butt_arcade
global.__objectDepths[32] = 0; // butt_blitz
global.__objectDepths[33] = 0; // butt_zen
global.__objectDepths[34] = 0; // butt_reset
global.__objectDepths[35] = 0; // butt_puzzle
global.__objectDepths[36] = 0; // obj_planet
global.__objectDepths[37] = 0; // ctrl
global.__objectDepths[38] = -1; // userbox
global.__objectDepths[39] = 0; // obj_menutextbox
global.__objectDepths[40] = 0; // stats_retrieve
global.__objectDepths[41] = 0; // sp1
global.__objectDepths[42] = -1000; // Gem
global.__objectDepths[43] = 0; // DissGem
global.__objectDepths[44] = -1001; // obj_gemoutlines
global.__objectDepths[45] = -1001; // bomb
global.__objectDepths[46] = -1002; // obj_shard
global.__objectDepths[47] = 0; // Coal
global.__objectDepths[48] = 0; // Coal_break
global.__objectDepths[49] = -1001; // geode
global.__objectDepths[50] = -1001; // geode_explode
global.__objectDepths[51] = -1003; // geode_text
global.__objectDepths[52] = 0; // time_slowdown
global.__objectDepths[53] = -1002; // fruit
global.__objectDepths[54] = -1002; // fruit_exp
global.__objectDepths[55] = -1500; // obj_ring
global.__objectDepths[56] = -1500; // obj_ring2
global.__objectDepths[57] = 0; // hypercube
global.__objectDepths[58] = 0; // hypercube_creator
global.__objectDepths[59] = 0; // hypercube_effect
global.__objectDepths[60] = -2000; // hypercube_sperm
global.__objectDepths[61] = -900; // click_ind
global.__objectDepths[62] = -1002; // lightningObj
global.__objectDepths[63] = -1500; // fruit_effect
global.__objectDepths[64] = -1009; // lightningkiller
global.__objectDepths[65] = -10000; // textellenter
global.__objectDepths[66] = 0; // shower
global.__objectDepths[67] = -1002; // tips
global.__objectDepths[68] = -1000; // dialog_box
global.__objectDepths[69] = -1001; // obj_OK
global.__objectDepths[70] = -1001; // obj_cancel
global.__objectDepths[71] = -1001; // obj_arrow1
global.__objectDepths[72] = -1001; // obj_arrow2
global.__objectDepths[73] = -2000; // cascade_text
global.__objectDepths[74] = -2000; // gems_text
global.__objectDepths[75] = -2001; // score_text
global.__objectDepths[76] = -2001; // score_text_big
global.__objectDepths[77] = -2002; // infobox
global.__objectDepths[78] = 0; // quest_obj
global.__objectDepths[79] = -1001; // lockAppear
global.__objectDepths[80] = -1001; // icelockAppear
global.__objectDepths[81] = -1001; // doomAppear
global.__objectDepths[82] = -1000; // lockGem
global.__objectDepths[83] = -1000; // icelockGem
global.__objectDepths[84] = -1001; // doomGem
global.__objectDepths[85] = -1001; // doompart
global.__objectDepths[86] = 1500; // Board
global.__objectDepths[87] = -1000; // stopper
global.__objectDepths[88] = -1001; // cover
global.__objectDepths[89] = 1501; // back_control
global.__objectDepths[90] = -1001; // obj_fade
global.__objectDepths[91] = -1002; // blitz_text
global.__objectDepths[92] = 0; // matcher
global.__objectDepths[93] = 0; // pointsObj
global.__objectDepths[94] = 0; // multiplier
global.__objectDepths[95] = -1001; // progressbar
global.__objectDepths[96] = 0; // boarddestroyer
global.__objectDepths[97] = 0; // stats
global.__objectDepths[98] = 0; // drawManager
global.__objectDepths[99] = 0; // obj_controller_wave
global.__objectDepths[100] = 0; // obj_player_wave


global.__objectNames[0] = "last_hurrah";
global.__objectNames[1] = "last_hurrahtext";
global.__objectNames[2] = "ch_selector";
global.__objectNames[3] = "chal_butt1";
global.__objectNames[4] = "chal_butt2";
global.__objectNames[5] = "chal_butt3";
global.__objectNames[6] = "chal_butt4";
global.__objectNames[7] = "chal_butt5";
global.__objectNames[8] = "ch_openfile";
global.__objectNames[9] = "ch_text_above";
global.__objectNames[10] = "Gamerule";
global.__objectNames[11] = "window_controller";
global.__objectNames[12] = "lock_setting";
global.__objectNames[13] = "icelock_setting";
global.__objectNames[14] = "coal_control";
global.__objectNames[15] = "doom_setting";
global.__objectNames[16] = "particle_control";
global.__objectNames[17] = "indicator_control";
global.__objectNames[18] = "options_master";
global.__objectNames[19] = "options_volumemus";
global.__objectNames[20] = "options_volumefx";
global.__objectNames[21] = "options_chk_vsync";
global.__objectNames[22] = "options_chk_2dlight";
global.__objectNames[23] = "obj_challenger";
global.__objectNames[24] = "obj_load";
global.__objectNames[25] = "but_options";
global.__objectNames[26] = "but_back";
global.__objectNames[27] = "wheel_spinner";
global.__objectNames[28] = "blackfade";
global.__objectNames[29] = "wheel_butt";
global.__objectNames[30] = "butt_classic";
global.__objectNames[31] = "butt_arcade";
global.__objectNames[32] = "butt_blitz";
global.__objectNames[33] = "butt_zen";
global.__objectNames[34] = "butt_reset";
global.__objectNames[35] = "butt_puzzle";
global.__objectNames[36] = "obj_planet";
global.__objectNames[37] = "ctrl";
global.__objectNames[38] = "userbox";
global.__objectNames[39] = "obj_menutextbox";
global.__objectNames[40] = "stats_retrieve";
global.__objectNames[41] = "sp1";
global.__objectNames[42] = "Gem";
global.__objectNames[43] = "DissGem";
global.__objectNames[44] = "obj_gemoutlines";
global.__objectNames[45] = "bomb";
global.__objectNames[46] = "obj_shard";
global.__objectNames[47] = "Coal";
global.__objectNames[48] = "Coal_break";
global.__objectNames[49] = "geode";
global.__objectNames[50] = "geode_explode";
global.__objectNames[51] = "geode_text";
global.__objectNames[52] = "time_slowdown";
global.__objectNames[53] = "fruit";
global.__objectNames[54] = "fruit_exp";
global.__objectNames[55] = "obj_ring";
global.__objectNames[56] = "obj_ring2";
global.__objectNames[57] = "hypercube";
global.__objectNames[58] = "hypercube_creator";
global.__objectNames[59] = "hypercube_effect";
global.__objectNames[60] = "hypercube_sperm";
global.__objectNames[61] = "click_ind";
global.__objectNames[62] = "lightningObj";
global.__objectNames[63] = "fruit_effect";
global.__objectNames[64] = "lightningkiller";
global.__objectNames[65] = "textellenter";
global.__objectNames[66] = "shower";
global.__objectNames[67] = "tips";
global.__objectNames[68] = "dialog_box";
global.__objectNames[69] = "obj_OK";
global.__objectNames[70] = "obj_cancel";
global.__objectNames[71] = "obj_arrow1";
global.__objectNames[72] = "obj_arrow2";
global.__objectNames[73] = "cascade_text";
global.__objectNames[74] = "gems_text";
global.__objectNames[75] = "score_text";
global.__objectNames[76] = "score_text_big";
global.__objectNames[77] = "infobox";
global.__objectNames[78] = "quest_obj";
global.__objectNames[79] = "lockAppear";
global.__objectNames[80] = "icelockAppear";
global.__objectNames[81] = "doomAppear";
global.__objectNames[82] = "lockGem";
global.__objectNames[83] = "icelockGem";
global.__objectNames[84] = "doomGem";
global.__objectNames[85] = "doompart";
global.__objectNames[86] = "Board";
global.__objectNames[87] = "stopper";
global.__objectNames[88] = "cover";
global.__objectNames[89] = "back_control";
global.__objectNames[90] = "obj_fade";
global.__objectNames[91] = "blitz_text";
global.__objectNames[92] = "matcher";
global.__objectNames[93] = "pointsObj";
global.__objectNames[94] = "multiplier";
global.__objectNames[95] = "progressbar";
global.__objectNames[96] = "boarddestroyer";
global.__objectNames[97] = "stats";
global.__objectNames[98] = "drawManager";
global.__objectNames[99] = "obj_controller_wave";
global.__objectNames[100] = "obj_player_wave";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for