//draw_self()
draw_set_font(font0)
draw_set_color(c_white)
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_text(x,y-32,"USERNAME")
draw_text_transformed(x,y,string_hash_to_newline(field + blink),1,1,0)